# ==============================
# COMMON CONFIG (ALL ENV)
# ==============================

spring:
  application:
    name: Ai Driven Ecommerce Backend

  config:
    import: optional:file:.env

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret-key: ${JWT_SECRET_KEY}

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

default:
  admin:
    username: ${DEFAULT_ADMIN_USERNAME}
    password: ${DEFAULT_ADMIN_PASSWORD}
    email: ${DEFAULT_ADMIN_EMAIL}
